const menuBtn=document.querySelector('#menuBtn'),nav=document.querySelector('#nav');
menuBtn?.addEventListener('click',()=>nav.classList.toggle('open'));
nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>nav.classList.remove('open')));
document.querySelector('#year').textContent=new Date().getFullYear();
const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('show')}),{threshold:.11});
document.querySelectorAll('.reveal').forEach(el=>io.observe(el));
const glow=document.querySelector('.cursor-glow');window.addEventListener('pointermove',e=>{if(glow){glow.style.left=e.clientX+'px';glow.style.top=e.clientY+'px'}});
const data={
 sirta:{tag:'1.’LİK ÖDÜLÜ',title:'SIRTA — Sürdürülebilir ve İnovatif Raylı Taşıma Ağı',image:'assets/images/sirta-solar-rail.webp',text:'Raylı ulaşım sistemlerini enerji verimliliği, yenilenebilir enerji entegrasyonu ve sürdürülebilir altyapı yaklaşımıyla ele alan proje. Ulaştırma ve Altyapı Bakanlığı tarafından düzenlenen Ulaşan ve Erişen Türkiye 2053 AR-GE Fikir Yarışması’nda Demir Yolu Projeleri kategorisinde birincilik elde eden ekipte yer aldım.',chips:['Rail','Sustainable Mobility','Renewable Energy']},
 tubitak:{tag:'TÜBİTAK 2209-A',title:'Deniz Araçlarının Uydu Görüntülerinden Tespit Edilmesi',image:'assets/images/tubitak-map.webp',text:'Uydu görüntüleri üzerinden deniz araçlarının tespitine yönelik veri analizleri gerçekleştirilen; arama-kurtarma operasyonlarında kullanılabilir bilgi üretmeye odaklanan tamamlanmış araştırma projesi.',chips:['Remote Sensing','Satellite Imagery','Marine Detection']},
 asra:{tag:'DEMİRYOLU',title:'ASRA — Akıllı ve Sürdürülebilir Demiryolu Altyapısı',image:'assets/images/asra-disaster.webp',text:'Fotovoltaik ve rüzgâr enerjisi, piezoelektrik üretim, yoğunluk sensörleri, afet tahliye koridorları, mobil sağlık ve lojistik vagonları gibi bileşenleri bütünleşik bir demiryolu altyapısında bir araya getiren konsept.',chips:['Smart Rail','Resilience','Energy']},
 mavi:{tag:'DENİZCİLİK',title:'MAVİ-2053 — Ulusal Deniz Karbon Yönetimi, Optimizasyon ve Afet Dayanıklılığı Modeli',image:'assets/images/mavi2053.webp',text:'Deniz ulaşımında karbon emisyonlarının CBS tabanlı izlenmesi ve azaltılması; dinamik deniz koridorları, yeşil liman elektrifikasyonu, MRV ve afet durumlarında denizden karaya lojistik destek yaklaşımı.',chips:['GIS','Maritime','Carbon','MRV','Resilience']},
 yol:{tag:'KARAYOLU',title:'YOL2053 — Akıllı, Dirençli ve Sürdürülebilir Karayolu',image:'assets/images/hero-road.webp',text:'Enerji üreten yol altyapısı, fotovoltaik koridorlar, dinamik şeritler, kablosuz şarj, IoT bakım sistemleri, yaya/yaban hayatı sensörleri ve akıllı güvenlik çözümlerini bir araya getiren gelecek karayolu yaklaşımı.',chips:['Smart Road','IoT','Solar','Autonomous Mobility']},
 offshore:{tag:'OFFSHORE WIND 2025',title:'Denizüstü Rüzgâr Türbinlerinde Hibrit Enerji Sistemleri',image:'assets/images/offshore-hybrid.webp',text:'Denizüstü rüzgâr türbinlerinin güneş ve dalga/hidroelektrik enerji sistemleriyle entegre edilerek aynı sahada çok kaynaklı yenilenebilir enerji üretimi sağlamasına yönelik sunum/proje yaklaşımı.',chips:['Offshore Wind','Wave Energy','Solar','Hybrid Systems']},
 smartcity:{tag:'AKILLI ŞEHİRLER',title:'İklim Dirençli ve Sürdürülebilir Kent Çalışmaları',image:'assets/images/green-smart.webp',text:'CBS, yeşil altyapı, sürdürülebilir ulaşım, yenilenebilir enerji ve iklim dayanıklılığını bir araya getiren şehir ölçekli proje ve konsept çalışmalarından seçkiler.',chips:['Smart City','GIS','Climate Resilience','Green Infrastructure']},
 digitaltwin:{tag:'GEOSPATIAL + AI',title:'Dijital İkiz & Akıllı Şehirler',image:'assets/images/digital-twin.webp',text:'Geomatik, CBS, uzaktan algılama ve yapay zekâ yöntemlerinin şehirlerin dijital temsilleri ve mekânsal karar destek sistemlerinde kullanımına yönelik araştırma yönelimi.',chips:['Digital Twin','Geomatics','GIS','AI']}
};
const dlg=document.querySelector('#projectDialog');
const close=()=>dlg?.close();document.querySelector('.dialog-close')?.addEventListener('click',close);dlg?.addEventListener('click',e=>{if(e.target===dlg)close()});
document.querySelectorAll('[data-project]').forEach(card=>card.addEventListener('click',()=>{const p=data[card.dataset.project];if(!p)return;document.querySelector('#dialogImage').src=p.image;document.querySelector('#dialogImage').alt=p.title;document.querySelector('#dialogTag').textContent=p.tag;document.querySelector('#dialogTitle').textContent=p.title;document.querySelector('#dialogText').textContent=p.text;document.querySelector('#dialogChips').innerHTML=p.chips.map(x=>`<span>${x}</span>`).join('');dlg.showModal()}));
